
const movies = [
  // ===== TERROR =====
  {
    id: 1,
    title: "Whistle: El silbido del mal",
    year: 2026,
    type: "movie",
    category: "Terror",
    rating: 7.2,
    featured: false,
    genres: ["Terror", "Thriller"],
    description: "Una familia se muda a una casa aislada en el campo donde un silbido sobrenatural aterroriza a sus habitantes cada noche.",
    poster: "https://image.tmdb.org/t/p/w500/84vAcFwxoObBuMWANWQXCg0Umg8.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/finq0JnC6tIMkKczzyxLJjgWFfT.jpg",
    duration: "1h 45min",
    director: "Corin Hardy"
  },
  {
    id: 2,
    title: "La sonrisa del mal (The Holy Boy)",
    year: 2026,
    type: "movie",
    category: "Terror",
    rating: 6.8,
    featured: false,
    genres: ["Terror", "Misterio"],
    description: "Un niño con poderes sobrenaturales aterroriza a un pequeño pueblo italiano mientras un sacerdote intenta detener el mal que se ha despertado.",
    poster: "https://placehold.co/500x750/0d0d0d/bb3333?text=The+Holy+Boy",
    backdrop: "https://placehold.co/1920x1080/0d0d0d/bb3333?text=The+Holy+Boy",
    duration: "1h 38min",
    director: "Paolo Strippoli"
  },
  {
    id: 3,
    title: "Te van a matar",
    year: 2026,
    type: "movie",
    category: "Terror",
    rating: 7.0,
    featured: false,
    genres: ["Terror", "Acción", "Thriller"],
    description: "Un hombre es perseguido implacablemente por un grupo misterioso con métodos cada vez más sádicos en una noche interminable de supervivencia.",
    poster: "https://placehold.co/500x750/110000/dd1111?text=Te+Van+a+Matar",
    backdrop: "https://placehold.co/1920x1080/110000/dd1111?text=Te+Van+a+Matar",
    duration: "1h 42min",
    director: "Kirill Sokolov"
  },
  {
    id: 4,
    title: "Caminando con el diablo",
    year: 2026,
    type: "movie",
    category: "Terror",
    rating: 6.5,
    featured: false,
    genres: ["Terror", "Drama"],
    description: "Una joven descubre que su familia está vinculada a un pacto ancestral con una entidad demoníaca en los montes del norte de España.",
    poster: "https://placehold.co/500x750/0a0a0a/aa2222?text=Caminando+con+el+Diablo",
    backdrop: "https://placehold.co/1920x1080/0a0a0a/aa2222?text=Caminando+con+el+Diablo",
    duration: "1h 50min",
    director: "Rubén Pérez Barrena"
  },

  // ===== SUSPENSE =====
  {
    id: 10,
    title: "El día de la revelación",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 8.5,
    featured: true,
    genres: ["Suspense", "Sci-Fi", "Drama"],
    description: "Steven Spielberg regresa al género que definió: la humanidad reacciona ante la prueba irrefutable de vida extraterrestre. ¿Y si la verdad estuviera a punto de ser revelada?",
    poster: "https://placehold.co/500x750/0a1628/4488cc?text=El+Dia+de+la+Revelacion",
    backdrop: "https://placehold.co/1920x1080/0a1628/4488cc?text=El+Dia+de+la+Revelacion",
    duration: "2h 20min",
    director: "Steven Spielberg"
  },
  {
    id: 11,
    title: "Spider-Man: Brand New Day",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 8.0,
    featured: true,
    genres: ["Acción", "Suspense", "Aventura"],
    description: "Peter Parker vuelve al anonimato total mientras enfrenta una Nueva York plagada de amenazas y un nuevo villano que conoce su mayor secreto.",
    poster: "https://image.tmdb.org/t/p/w500/9JCQtDCSpPR2ld55yNlEg1VwcQo.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/9JCQtDCSpPR2ld55yNlEg1VwcQo.jpg",
    duration: "2h 25min",
    director: "Destin Daniel Cretton"
  },
  {
    id: 12,
    title: "Supergirl: Woman of Tomorrow",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 7.6,
    featured: false,
    genres: ["Acción", "Suspense", "Sci-Fi"],
    description: "Kara Zor-El se embarca en una misión de venganza junto a una joven que ha perdido a su familia, descubriendo lo que significa ser una heroína.",
    poster: "https://image.tmdb.org/t/p/w500/niSvU02l2BONH9ivubV6K1a5QiK.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/niSvU02l2BONH9ivubV6K1a5QiK.jpg",
    duration: "2h 10min",
    director: "Craig Gillespie"
  },
  {
    id: 13,
    title: "Los juegos del hambre: Amanecer en la cosecha",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 7.8,
    featured: true,
    genres: ["Suspense", "Acción", "Drama"],
    description: "La juventud de Haymitch Abernathy: lucha por sobrevivir en los Quincuagésimos Juegos del Hambre, donde se seleccionan el doble de tributos.",
    poster: "https://image.tmdb.org/t/p/w500/kONfwpf0AZzvL1zqjZV9C89g1PY.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/kONfwpf0AZzvL1zqjZV9C89g1PY.jpg",
    duration: "2h 30min",
    director: "Francis Lawrence"
  },
  {
    id: 14,
    title: "Proyecto Salvación",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 7.9,
    featured: false,
    genres: ["Suspense", "Sci-Fi", "Aventura"],
    description: "Un astronauta solitario en una misión desesperada para salvar la Tierra descubre que no está solo en el espacio.",
    poster: "https://image.tmdb.org/t/p/w500/vOhW7Lbt4kZAqe0vJhVC4Ced9x2.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/vOhW7Lbt4kZAqe0vJhVC4Ced9x2.jpg",
    duration: "2h 15min",
    director: "Phil Lord, Christopher Miller"
  },
  {
    id: 15,
    title: "Peaky Blinders: El hombre inmortal",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 8.3,
    featured: true,
    genres: ["Suspense", "Crimen", "Drama"],
    description: "Tommy Shelby regresa durante la Segunda Guerra Mundial, arrastrado a los rincones más oscuros de Birmingham en misiones clandestinas.",
    poster: "https://image.tmdb.org/t/p/w500/gRMalasZEzsZi4w2VFuYusfSfqf.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/gRMalasZEzsZi4w2VFuYusfSfqf.jpg",
    duration: "2h 30min",
    director: "Tom Harper"
  },
  {
    id: 16,
    title: "Street Fighter",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 7.1,
    featured: false,
    genres: ["Acción", "Suspense", "Aventura"],
    description: "Ambientada en 1993, Ryu y Ken son reclutados por Chun-Li para el Torneo Mundial de Guerreros, tras el que se esconde una conspiración mortal.",
    poster: "https://image.tmdb.org/t/p/w500/kFsjvIZBt6uJ4dVNCsdTVooBx4k.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/kFsjvIZBt6uJ4dVNCsdTVooBx4k.jpg",
    duration: "2h 5min",
    director: "Kitao Sakurai"
  },
  {
    id: 17,
    title: "Shelter: El protector",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 7.0,
    featured: false,
    genres: ["Acción", "Suspense"],
    description: "Un exmilitar debe proteger a una familia refugiada en un búnker subterráneo cuando una amenaza desconocida arrasa la superficie.",
    poster: "https://placehold.co/500x750/1a1a2e/6688bb?text=Shelter",
    backdrop: "https://placehold.co/1920x1080/1a1a2e/6688bb?text=Shelter",
    duration: "1h 55min",
    director: "Ric Roman Waugh"
  },
  {
    id: 18,
    title: "Cleaner: Rescate vertical",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 7.3,
    featured: false,
    genres: ["Acción", "Suspense", "Thriller"],
    description: "Un limpiacristales queda atrapado en un rascacielos tomado por terroristas y debe escalar planta a planta para rescatar a los rehenes.",
    poster: "https://image.tmdb.org/t/p/w500/mwzDApMZAGeYCEVjhegKvCzDX0W.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/gsQJOfeW45KLiQeEIsom94QPQwb.jpg",
    duration: "1h 48min",
    director: "Martin Campbell"
  },
  {
    id: 19,
    title: "Águilas de El Cairo",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 7.4,
    featured: false,
    genres: ["Suspense", "Drama", "Thriller"],
    description: "Un agente encubierto se infiltra en una red de espionaje internacional con sede en El Cairo, donde las lealtades cambian a cada segundo.",
    poster: "https://placehold.co/500x750/2a1a0a/cc9944?text=Aguilas+de+El+Cairo",
    backdrop: "https://placehold.co/1920x1080/2a1a0a/cc9944?text=Aguilas+de+El+Cairo",
    duration: "2h 0min",
    director: "Tarik Saleh"
  },

  // ===== DRAMA =====
  {
    id: 20,
    title: "Hamnet",
    year: 2025,
    type: "movie",
    category: "Drama",
    rating: 8.2,
    featured: true,
    genres: ["Drama", "Historia"],
    description: "La vida del hijo de Shakespeare y las raíces emocionales detrás de la creación de Hamlet. Agnes lidia con la enfermedad de su hijo en la Inglaterra del siglo XVI.",
    poster: "https://image.tmdb.org/t/p/w500/vbeyOZm2bvBXcbgPD3v6o94epPX.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/vbeyOZm2bvBXcbgPD3v6o94epPX.jpg",
    duration: "2h 5min",
    director: "Chloé Zhao"
  },
  {
    id: 21,
    title: "Marty Supreme",
    year: 2025,
    type: "movie",
    category: "Drama",
    rating: 8.0,
    featured: true,
    genres: ["Drama", "Biografía"],
    description: "Timothée Chalamet interpreta a un joven ambicioso en la Nueva York de los 50 que se transforma de buscavidas en icono del tenis de mesa.",
    poster: "https://image.tmdb.org/t/p/w500/lYWEXbQgRTR4ZQleSXAgRbxAjvq.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/lYWEXbQgRTR4ZQleSXAgRbxAjvq.jpg",
    duration: "2h 29min",
    director: "Josh Safdie"
  },
  {
    id: 22,
    title: "Cumbres borrascosas",
    year: 2026,
    type: "movie",
    category: "Drama",
    rating: 7.8,
    featured: true,
    genres: ["Drama", "Romance"],
    description: "Margot Robbie y Jacob Elordi protagonizan la nueva adaptación de Emerald Fennell del clásico de Emily Brontë: obsesión, resentimiento y amor destructivo.",
    poster: "https://image.tmdb.org/t/p/w500/3YBce6dTh1D5oCMITXk2S5QhPt.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/3YBce6dTh1D5oCMITXk2S5QhPt.jpg",
    duration: "2h 15min",
    director: "Emerald Fennell"
  },
  {
    id: 23,
    title: "I Swear (Incontrolable)",
    year: 2026,
    type: "movie",
    category: "Drama",
    rating: 7.5,
    featured: false,
    genres: ["Drama", "Biografía"],
    description: "La historia real de John Davidson, diagnosticado con síndrome de Tourette en su adolescencia, y su lucha por la comprensión y la visibilidad.",
    poster: "https://placehold.co/500x750/1a1a2e/8899bb?text=I+Swear",
    backdrop: "https://placehold.co/1920x1080/1a1a2e/8899bb?text=I+Swear",
    duration: "2h 0min",
    director: "Kirk Jones"
  },
  {
    id: 24,
    title: "Michael",
    year: 2026,
    type: "movie",
    category: "Drama",
    rating: 7.9,
    featured: true,
    genres: ["Drama", "Biografía", "Musical"],
    description: "El primer biopic cinematográfico de Michael Jackson, desde los Jackson Five hasta su consagración como Rey del Pop. Jaafar Jackson interpreta a su tío.",
    poster: "https://image.tmdb.org/t/p/w500/3Qud19bBUrrJAzy0Ilm8gRJlJXP.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/3Qud19bBUrrJAzy0Ilm8gRJlJXP.jpg",
    duration: "2h 30min",
    director: "Antoine Fuqua"
  },
  {
    id: 25,
    title: "Amarga Navidad",
    year: 2026,
    type: "movie",
    category: "Drama",
    rating: 8.1,
    featured: true,
    genres: ["Drama"],
    description: "La nueva película de Pedro Almodóvar. Un drama íntimo y desgarrador ambientado durante las fiestas navideñas que explora las tensiones familiares.",
    poster: "https://placehold.co/500x750/2a0a0a/cc6644?text=Amarga+Navidad",
    backdrop: "https://placehold.co/1920x1080/2a0a0a/cc6644?text=Amarga+Navidad",
    duration: "2h 10min",
    director: "Pedro Almodóvar"
  },
  {
    id: 26,
    title: "¡La novia!",
    year: 2026,
    type: "movie",
    category: "Drama",
    rating: 7.7,
    featured: false,
    genres: ["Drama", "Romance", "Fantasía"],
    description: "Maggie Gyllenhaal dirige a Christian Bale y Jessie Buckley en una reimaginación oscura y poética del mito de Frankenstein.",
    poster: "https://image.tmdb.org/t/p/w500/lV8YHwGkYZsm6EfIqnhaSz2avKt.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/lV8YHwGkYZsm6EfIqnhaSz2avKt.jpg",
    duration: "2h 0min",
    director: "Maggie Gyllenhaal"
  },
  {
    id: 27,
    title: "Digger",
    year: 2026,
    type: "movie",
    category: "Drama",
    rating: 8.0,
    featured: false,
    genres: ["Drama", "Comedia", "Sátira"],
    description: "Tom Cruise interpreta a Digger Rockwell, el hombre más poderoso del mundo que debe salvar a la humanidad de un gran desastre. Una sátira de Iñárritu.",
    poster: "https://placehold.co/500x750/1c1c28/7788aa?text=Digger",
    backdrop: "https://placehold.co/1920x1080/1c1c28/7788aa?text=Digger",
    duration: "2h 25min",
    director: "Alejandro González Iñárritu"
  },

  // ===== HISTÓRICAS =====
  {
    id: 30,
    title: "La odisea",
    year: 2026,
    type: "movie",
    category: "Históricas",
    rating: 9.0,
    featured: true,
    genres: ["Aventura", "Drama", "Historia"],
    description: "Christopher Nolan reinterpreta el poema homérico con Matt Damon, Tom Holland, Zendaya y Anne Hathaway. Ulises lucha por regresar a Ítaca tras la guerra de Troya.",
    poster: "https://image.tmdb.org/t/p/w500/pe5cCoX5iIb5IWKPsbPkCwjLFHt.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/pe5cCoX5iIb5IWKPsbPkCwjLFHt.jpg",
    duration: "2h 50min",
    director: "Christopher Nolan"
  },
  {
    id: 31,
    title: "El último vikingo",
    year: 2026,
    type: "movie",
    category: "Históricas",
    rating: 7.3,
    featured: false,
    genres: ["Drama", "Historia", "Acción"],
    description: "La historia del último gran rey vikingo y su lucha desesperada por mantener viva una civilización en declive.",
    poster: "https://placehold.co/500x750/1a1510/aa8844?text=El+Ultimo+Vikingo",
    backdrop: "https://placehold.co/1920x1080/1a1510/aa8844?text=El+Ultimo+Vikingo",
    duration: "2h 15min",
    director: "Anders Thomas Jensen"
  },
  {
    id: 32,
    title: "El mago del Kremlin",
    year: 2026,
    type: "movie",
    category: "Históricas",
    rating: 7.5,
    featured: false,
    genres: ["Drama", "Historia", "Thriller"],
    description: "Adaptación de la novela sobre Vladislav Surkov, el enigmático asesor político que controló la narrativa del Kremlin durante dos décadas.",
    poster: "https://placehold.co/500x750/1a0a0a/cc8833?text=El+Mago+del+Kremlin",
    backdrop: "https://placehold.co/1920x1080/1a0a0a/cc8833?text=El+Mago+del+Kremlin",
    duration: "2h 10min",
    director: "Olivier Assayas"
  },
  {
    id: 33,
    title: "La sombra de mi padre",
    year: 2026,
    type: "movie",
    category: "Históricas",
    rating: 7.1,
    featured: false,
    genres: ["Drama", "Historia"],
    description: "Un joven africano descubre los secretos del pasado colonial de su familia y las sombras que aún persisten en el presente.",
    poster: "https://placehold.co/500x750/1a1008/997744?text=La+Sombra+de+Mi+Padre",
    backdrop: "https://placehold.co/1920x1080/1a1008/997744?text=La+Sombra+de+Mi+Padre",
    duration: "1h 55min",
    director: "Akinola Davies"
  },

  // ===== COMEDIAS =====
  {
    id: 40,
    title: "Torrente presidente",
    year: 2026,
    type: "movie",
    category: "Comedias",
    rating: 6.5,
    featured: true,
    genres: ["Comedia"],
    description: "Santiago Segura regresa con la franquicia más gamberra del cine español. Torrente se presenta a presidente del gobierno con resultados hilarantes.",
    poster: "https://placehold.co/500x750/2a1a00/ffaa33?text=Torrente+Presidente",
    backdrop: "https://placehold.co/1920x1080/2a1a00/ffaa33?text=Torrente+Presidente",
    duration: "1h 50min",
    director: "Santiago Segura"
  },
  {
    id: 41,
    title: "El diablo viste de Prada 2",
    year: 2026,
    type: "movie",
    category: "Comedias",
    rating: 7.5,
    featured: true,
    genres: ["Comedia", "Drama"],
    description: "Meryl Streep, Anne Hathaway y Emily Blunt regresan. Miranda Priestly enfrenta el declive de las revistas impresas mientras Andy triunfa en el mundo digital.",
    poster: "https://image.tmdb.org/t/p/w500/xTI42pmsP5EDnvsNJPEDubwWBQO.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xTI42pmsP5EDnvsNJPEDubwWBQO.jpg",
    duration: "2h 0min",
    director: "David Frankel"
  },
  {
    id: 42,
    title: "Jackass 5",
    year: 2026,
    type: "movie",
    category: "Comedias",
    rating: 6.8,
    featured: false,
    genres: ["Comedia"],
    description: "Johnny Knoxville y el equipo vuelven con retos, bromas y acrobacias tan peligrosas como descacharrantes. El caos sin filtros regresa.",
    poster: "https://placehold.co/500x750/2a2000/ffcc00?text=Jackass+5",
    backdrop: "https://placehold.co/1920x1080/2a2000/ffcc00?text=Jackass+5",
    duration: "1h 40min",
    director: "Jeff Tremaine"
  },
  {
    id: 43,
    title: "Aída y vuelta",
    year: 2026,
    type: "movie",
    category: "Comedias",
    rating: 6.9,
    featured: false,
    genres: ["Comedia"],
    description: "Comedia española con Carmen Machi, Paco León y Miren Ibarguren. Una aventura cómica con personajes desternillantes.",
    poster: "https://placehold.co/500x750/2a1a10/eebb44?text=Aida+y+Vuelta",
    backdrop: "https://placehold.co/1920x1080/2a1a10/eebb44?text=Aida+y+Vuelta",
    duration: "1h 45min",
    director: "Secun de la Rosa"
  },
  {
    id: 44,
    title: "Altas capacidades",
    year: 2026,
    type: "movie",
    category: "Comedias",
    rating: 7.2,
    featured: false,
    genres: ["Comedia", "Drama"],
    description: "Una comedia dramática española sobre un grupo de superdotados que se reúnen en un centro de convivencia con resultados inesperados.",
    poster: "https://placehold.co/500x750/1a1a0a/ddcc44?text=Altas+Capacidades",
    backdrop: "https://placehold.co/1920x1080/1a1a0a/ddcc44?text=Altas+Capacidades",
    duration: "1h 52min",
    director: "Víctor García León"
  },

  // ===== INFANTILES =====
  {
    id: 50,
    title: "Hoppers",
    year: 2026,
    type: "movie",
    category: "Infantiles",
    rating: 7.8,
    featured: true,
    genres: ["Animación", "Aventura", "Comedia"],
    description: "Nueva película de Pixar. Mabel descubre una tecnología que transfiere la conciencia humana a animales robóticos y 'salta' su mente a un castor.",
    poster: "https://image.tmdb.org/t/p/w500/xjtWQ2CL1mpmMNwuU5HeS4Iuwuu.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xjtWQ2CL1mpmMNwuU5HeS4Iuwuu.jpg",
    duration: "1h 40min",
    director: "Daniel Chong"
  },
  {
    id: 51,
    title: "Super Mario Galaxy: La película",
    year: 2026,
    type: "movie",
    category: "Infantiles",
    rating: 7.5,
    featured: true,
    genres: ["Animación", "Aventura", "Comedia"],
    description: "Mario y Luigi son transportados más allá del Reino Champiñón. Con la ayuda de Rosalina y los Lumas, deberán salvar el universo.",
    poster: "https://image.tmdb.org/t/p/w500/4msKOk5QsvZk7AHY5c3vgbUN8WB.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/4msKOk5QsvZk7AHY5c3vgbUN8WB.jpg",
    duration: "1h 35min",
    director: "Aaron Horvath, Michael Jelenic"
  },
  {
    id: 52,
    title: "Toy Story 5",
    year: 2026,
    type: "movie",
    category: "Infantiles",
    rating: 8.0,
    featured: true,
    genres: ["Animación", "Aventura", "Comedia"],
    description: "Pixar regresa a su saga más emblemática. Woody emprende un viaje para reencontrarse con antiguos amigos y descubrir qué significa pertenecer.",
    poster: "https://image.tmdb.org/t/p/w500/gaiMtK2ll6BLdK1qKFuZGDwwEuD.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/gaiMtK2ll6BLdK1qKFuZGDwwEuD.jpg",
    duration: "1h 38min",
    director: "Andrew Stanton"
  },
  {
    id: 53,
    title: "Minions y Monstruos",
    year: 2026,
    type: "movie",
    category: "Infantiles",
    rating: 7.2,
    featured: false,
    genres: ["Animación", "Comedia", "Aventura"],
    description: "Los entrañables Minions regresan con nuevas aventuras hilarantes y caóticas conectadas al arco narrativo de Gru.",
    poster: "https://placehold.co/500x750/2a2a00/ffdd33?text=Minions+y+Monstruos",
    backdrop: "https://placehold.co/1920x1080/2a2a00/ffdd33?text=Minions+y+Monstruos",
    duration: "1h 30min",
    director: "Pierre Coffin"
  },
  {
    id: 54,
    title: "The Mandalorian and Grogu",
    year: 2026,
    type: "movie",
    category: "Infantiles",
    rating: 8.2,
    featured: true,
    genres: ["Aventura", "Sci-Fi", "Familiar"],
    description: "Din Djarin y Grogu llegan a la gran pantalla. Su búsqueda de un nuevo hogar los enfrenta a enemigos del pasado y al legado de los Jedi.",
    poster: "https://image.tmdb.org/t/p/w500/m8lEffySgTuKxN3VsMd2gdgx1aw.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/m8lEffySgTuKxN3VsMd2gdgx1aw.jpg",
    duration: "2h 5min",
    director: "Jon Favreau"
  },
  {
    id: 55,
    title: "Mary Anning y la playa de los dinosaurios",
    year: 2026,
    type: "movie",
    category: "Infantiles",
    rating: 7.0,
    featured: false,
    genres: ["Animación", "Aventura", "Familiar"],
    description: "La historia animada de Mary Anning, la joven paleontóloga que descubrió fósiles que cambiaron la ciencia en la costa de Dorset.",
    poster: "https://placehold.co/500x750/0a2a1a/44bb88?text=Mary+Anning",
    backdrop: "https://placehold.co/1920x1080/0a2a1a/44bb88?text=Mary+Anning",
    duration: "1h 25min",
    director: "Marcel Barelli"
  }
];

const tvShows = [
  // ===== NETFLIX =====
  {
    id: 101,
    title: "Él y ella",
    year: 2026,
    type: "series",
    platform: "Netflix",
    category: "Suspense",
    rating: 8.0,
    featured: true,
    genres: ["Suspense", "Drama", "Thriller"],
    description: "Tessa Thompson y Jon Bernthal protagonizan este thriller: Anna investiga un asesinato en su pueblo natal y el detective la convierte en sospechosa. Toda historia tiene dos versiones.",
    poster: "https://placehold.co/500x750/1a0a0a/e50914?text=El+y+Ella",
    backdrop: "https://placehold.co/1920x1080/1a0a0a/e50914?text=El+y+Ella",
    seasons: 1,
    episodes: 6
  },
  {
    id: 102,
    title: "Los Bridgerton T4",
    year: 2026,
    type: "series",
    platform: "Netflix",
    category: "Drama",
    rating: 8.3,
    featured: true,
    genres: ["Drama", "Romance"],
    description: "Benedict Bridgerton se enamora de la misteriosa Sophie Beckett en un baile de máscaras. Amor, secretos y tensiones sociales en la temporada más romántica.",
    poster: "https://image.tmdb.org/t/p/w500/uXTg565ahu9RwonCX1V2Hex1NU6.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/iVadPLeLVb97RznIGDkswxtBzi6.jpg",
    seasons: 4,
    episodes: 8
  },
  {
    id: 103,
    title: "Salvador",
    year: 2026,
    type: "series",
    platform: "Netflix",
    category: "Drama",
    rating: 7.8,
    featured: false,
    genres: ["Drama", "Acción"],
    description: "Luis Tosar interpreta a un técnico de emergencias que descubre que su hija pertenece a un grupo ultra. Creada por Aitor Gabilondo, dirigida por Daniel Calparsoro.",
    poster: "https://placehold.co/500x750/0a0a0a/e50914?text=Salvador",
    backdrop: "https://placehold.co/1920x1080/0a0a0a/e50914?text=Salvador",
    seasons: 1,
    episodes: 8
  },
  {
    id: 104,
    title: "One Piece: Rumbo a la Grand Line T2",
    year: 2026,
    type: "series",
    platform: "Netflix",
    category: "Comedias",
    rating: 8.5,
    featured: true,
    genres: ["Aventura", "Acción", "Comedia"],
    description: "Luffy y los Sombrero de Paja navegan la Grand Line: islas impredecibles, piratas letales y fenómenos imposibles. Iñaki Godoy regresa como Luffy.",
    poster: "https://image.tmdb.org/t/p/w500/blWCPEqDGLBuLB9u89CxP9ORQP4.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/qD211Hb5XwFxrszzBBe5EUYJerh.jpg",
    seasons: 2,
    episodes: 8
  },
  {
    id: 105,
    title: "Berlín y la dama del armiño T2",
    year: 2026,
    type: "series",
    platform: "Netflix",
    category: "Suspense",
    rating: 7.6,
    featured: false,
    genres: ["Suspense", "Crimen", "Drama"],
    description: "Pedro Alonso regresa como Berlín con un nuevo golpe en Sevilla: fingir robar la dama del armiño mientras su verdadero objetivo es un matrimonio que lo chantajea.",
    poster: "https://placehold.co/500x750/0d0a0a/e50914?text=Berlin+T2",
    backdrop: "https://placehold.co/1920x1080/0d0a0a/e50914?text=Berlin+T2",
    seasons: 2,
    episodes: 8
  },
  {
    id: 106,
    title: "Cien años de soledad T2",
    year: 2026,
    type: "series",
    platform: "Netflix",
    category: "Drama",
    rating: 8.7,
    featured: true,
    genres: ["Drama", "Fantasía"],
    description: "La segunda y última parte de la adaptación de la obra maestra de Gabriel García Márquez. Rodada íntegramente en Colombia con respaldo de la familia del autor.",
    poster: "https://placehold.co/500x750/1a1008/e50914?text=Cien+Anos+de+Soledad+T2",
    backdrop: "https://placehold.co/1920x1080/1a1008/e50914?text=Cien+Anos+de+Soledad+T2",
    seasons: 2,
    episodes: 8
  },
  {
    id: 107,
    title: "Bronca T2",
    year: 2026,
    type: "series",
    platform: "Netflix",
    category: "Suspense",
    rating: 7.9,
    featured: false,
    genres: ["Suspense", "Drama", "Comedia"],
    description: "Oscar Isaac, Carey Mulligan y Cailee Spaeny. Una pareja presencia una pelea violenta que desencadena chantajes y tensiones en un exclusivo country club.",
    poster: "https://placehold.co/500x750/100a0a/e50914?text=Bronca+T2",
    backdrop: "https://placehold.co/1920x1080/100a0a/e50914?text=Bronca+T2",
    seasons: 2,
    episodes: 8
  },

  // ===== HBO =====
  {
    id: 110,
    title: "The Pitt T2",
    year: 2026,
    type: "series",
    platform: "HBO",
    category: "Drama",
    rating: 8.2,
    featured: false,
    genres: ["Drama"],
    description: "Noah Wyle regresa como el médico jefe Robby en la sala de urgencias de Pittsburgh. Cada episodio cubre en tiempo real una hora de un turno de 15 horas.",
    poster: "https://image.tmdb.org/t/p/w500/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/q1z0W19F4T5Xs2qka3xJSmFjv9a.jpg",
    seasons: 2,
    episodes: 15
  },
  {
    id: 111,
    title: "El caballero de los Siete Reinos",
    year: 2026,
    type: "series",
    platform: "HBO",
    category: "Drama",
    rating: 8.5,
    featured: true,
    genres: ["Drama", "Fantasía", "Aventura"],
    description: "Spin-off de Juego de Tronos basado en 'Cuentos de Dunk y Egg'. Ser Duncan y su escudero Egg recorren Poniente un siglo antes de los eventos de la saga principal.",
    poster: "https://image.tmdb.org/t/p/w500/k8yARbD9iYn2nRX2HvsopfKDN2r.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/k8yARbD9iYn2nRX2HvsopfKDN2r.jpg",
    seasons: 1,
    episodes: 6
  },
  {
    id: 112,
    title: "Euphoria T3",
    year: 2026,
    type: "series",
    platform: "HBO",
    category: "Drama",
    rating: 8.4,
    featured: true,
    genres: ["Drama"],
    description: "Zendaya regresa como Rue. Los personajes, ya adultos, enfrentan consecuencias psicológicas del pasado: rupturas, ambiciones y búsqueda de identidad.",
    poster: "https://image.tmdb.org/t/p/w500/3Q0hd3heuWwDWpwcDkhQOA6TYWI.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/9KnIzPCv9XpWA0MqmwiKBZvV1Sj.jpg",
    seasons: 3,
    episodes: 8
  },
  {
    id: 113,
    title: "La Casa del Dragón T3",
    year: 2026,
    type: "series",
    platform: "HBO",
    category: "Drama",
    rating: 8.8,
    featured: true,
    genres: ["Drama", "Fantasía", "Acción"],
    description: "La Danza de los Dragones se intensifica: alianzas imposibles, ciudades arrasadas y dragones enfrentados en cielo abierto por el Trono de Hierro.",
    poster: "https://image.tmdb.org/t/p/w500/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
    seasons: 3,
    episodes: 8
  },
  {
    id: 114,
    title: "Rooster",
    year: 2026,
    type: "series",
    platform: "HBO",
    category: "Comedias",
    rating: 7.8,
    featured: false,
    genres: ["Comedia", "Drama"],
    description: "Steve Carell regresa a la comedia TV. Un escritor en crisis lidia con su relación con su hija en un entorno universitario. Producida por Bill Lawrence.",
    poster: "https://placehold.co/500x750/0a0a1a/9b59b6?text=Rooster",
    backdrop: "https://placehold.co/1920x1080/0a0a1a/9b59b6?text=Rooster",
    seasons: 1,
    episodes: 10
  },
  {
    id: 115,
    title: "Lanterns",
    year: 2026,
    type: "series",
    platform: "HBO",
    category: "Suspense",
    rating: 8.0,
    featured: true,
    genres: ["Suspense", "Sci-Fi", "Acción"],
    description: "Hal Jordan y John Stewart investigan un caso al estilo True Detective que conecta con el nuevo universo DC de James Gunn. Kyle Chandler y Aaron Pierre protagonizan.",
    poster: "https://image.tmdb.org/t/p/w500/moA5NNpOsSeQ2gNkOBgbMeNOl3d.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/moA5NNpOsSeQ2gNkOBgbMeNOl3d.jpg",
    seasons: 1,
    episodes: 8
  },

  // ===== MOVISTAR =====
  {
    id: 120,
    title: "Riot Women",
    year: 2026,
    type: "series",
    platform: "Movistar",
    category: "Drama",
    rating: 7.5,
    featured: false,
    genres: ["Drama", "Acción"],
    description: "Un grupo de mujeres rebeldes lucha contra la opresión en una sociedad distópica en esta nueva producción original de Movistar Plus+.",
    poster: "https://placehold.co/500x750/0a0a2a/0088cc?text=Riot+Women",
    backdrop: "https://placehold.co/1920x1080/0a0a2a/0088cc?text=Riot+Women",
    seasons: 1,
    episodes: 8
  },
  {
    id: 121,
    title: "Outlander T8",
    year: 2026,
    type: "series",
    platform: "Movistar",
    category: "Drama",
    rating: 8.1,
    featured: true,
    genres: ["Drama", "Romance", "Historia"],
    description: "La temporada final de la épica saga de Claire y Jamie Fraser. Tras ocho temporadas de viajes en el tiempo, amor y guerra, la historia llega a su conclusión.",
    poster: "https://image.tmdb.org/t/p/w500/bxBmfyzK0ARF9hqf2pbFWsddH14.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/nf3Vlxm3C9U1aKUUQHmKFZmxPSc.jpg",
    seasons: 8,
    episodes: 10
  },
  {
    id: 122,
    title: "Por cien millones",
    year: 2026,
    type: "series",
    platform: "Movistar",
    category: "Suspense",
    rating: 7.6,
    featured: false,
    genres: ["Suspense", "Drama", "Crimen"],
    description: "Un grupo de personas normales se enfrenta a un dilema moral cuando descubren cien millones de euros escondidos, desatando caos y traiciones.",
    poster: "https://placehold.co/500x750/0a0a1a/2288bb?text=Por+Cien+Millones",
    backdrop: "https://placehold.co/1920x1080/0a0a1a/2288bb?text=Por+Cien+Millones",
    seasons: 1,
    episodes: 6
  },

  // ===== APPLE TV+ =====
  {
    id: 130,
    title: "Furtivo",
    year: 2026,
    type: "series",
    platform: "Apple",
    category: "Suspense",
    rating: 7.9,
    featured: true,
    genres: ["Suspense", "Drama", "Thriller"],
    description: "Un guardabosques descubre una red de caza furtiva que esconde algo mucho más siniestro en los bosques del norte de España. Producción de Apple TV+.",
    poster: "https://placehold.co/500x750/1a1a1a/aaaaaa?text=Furtivo",
    backdrop: "https://placehold.co/1920x1080/1a1a1a/aaaaaa?text=Furtivo",
    seasons: 1,
    episodes: 8
  },
  {
    id: 131,
    title: "Mujeres imperfectas",
    year: 2026,
    type: "series",
    platform: "Apple",
    category: "Drama",
    rating: 7.7,
    featured: false,
    genres: ["Drama", "Comedia"],
    description: "Tres amigas muy diferentes navegan los retos de la vida moderna mientras intentan mantener viva su amistad en esta nueva serie de Apple TV+.",
    poster: "https://placehold.co/500x750/1a1a1a/999999?text=Mujeres+Imperfectas",
    backdrop: "https://placehold.co/1920x1080/1a1a1a/999999?text=Mujeres+Imperfectas",
    seasons: 1,
    episodes: 10
  },

  // ===== PRIME VIDEO =====
  {
    id: 140,
    title: "Spider-Noir",
    year: 2026,
    type: "series",
    platform: "Prime",
    category: "Suspense",
    rating: 8.3,
    featured: true,
    genres: ["Suspense", "Acción", "Crimen"],
    description: "Nicolas Cage protagoniza la versión noir de Spider-Man: un detective privado en el Nueva York corrupto de los años 30 durante la Gran Depresión.",
    poster: "https://image.tmdb.org/t/p/w500/cRAzL6mmdM6Q6UuQgc335UMgcfd.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/qfbVc3kuVqBEgxpon1nBRF1t9KT.jpg",
    seasons: 1,
    episodes: 8
  },
  {
    id: 141,
    title: "Blade Runner 2099",
    year: 2026,
    type: "series",
    platform: "Prime",
    category: "Suspense",
    rating: 8.5,
    featured: true,
    genres: ["Sci-Fi", "Suspense", "Drama"],
    description: "Michelle Yeoh protagoniza esta secuela ambientada 50 años después de 2049. La línea entre humanos y replicantes es más difusa que nunca.",
    poster: "https://placehold.co/500x750/0a1020/00a8e1?text=Blade+Runner+2099",
    backdrop: "https://placehold.co/1920x1080/0a1020/00a8e1?text=Blade+Runner+2099",
    seasons: 1,
    episodes: 6
  },
  {
    id: 142,
    title: "Invencible T4",
    year: 2026,
    type: "series",
    platform: "Prime",
    category: "Suspense",
    rating: 8.6,
    featured: true,
    genres: ["Animación", "Acción", "Suspense"],
    description: "Mark Grayson continúa su camino como el superhéroe más poderoso de la Tierra mientras enfrenta amenazas cósmicas y dilemas morales cada vez más complejos.",
    poster: "https://image.tmdb.org/t/p/w500/uPmxchXSXDXTYXe8OKWgmV9TowB.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/dfmPbyeZZSz3bekeESvMJaH91gS.jpg",
    seasons: 4,
    episodes: 8
  },
  {
    id: 143,
    title: "El joven Sherlock",
    year: 2026,
    type: "series",
    platform: "Prime",
    category: "Suspense",
    rating: 7.7,
    featured: false,
    genres: ["Suspense", "Misterio", "Drama"],
    description: "Los años de formación de Sherlock Holmes: un joven brillante pero inadaptado comienza a resolver sus primeros casos en la Inglaterra victoriana.",
    poster: "https://placehold.co/500x750/0d0d1a/00a8e1?text=El+Joven+Sherlock",
    backdrop: "https://placehold.co/1920x1080/0d0d1a/00a8e1?text=El+Joven+Sherlock",
    seasons: 1,
    episodes: 8
  },

  // ===== DISNEY+ =====
  {
    id: 150,
    title: "Wonder Man",
    year: 2026,
    type: "series",
    platform: "Disney",
    category: "Comedias",
    rating: 7.5,
    featured: true,
    genres: ["Comedia", "Acción", "Superhéroes"],
    description: "Simon Williams, actor fracasado, compite con Trevor Slattery por el papel de Wonder Man. Marvel mezcla comedia, acción y cine dentro del cine.",
    poster: "https://image.tmdb.org/t/p/w500/6yy9nQlFt2l6UVWzrfhszFCaZ5C.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/6yy9nQlFt2l6UVWzrfhszFCaZ5C.jpg",
    seasons: 1,
    episodes: 8
  },
  {
    id: 151,
    title: "Daredevil: Born Again T2",
    year: 2026,
    type: "series",
    platform: "Disney",
    category: "Suspense",
    rating: 8.5,
    featured: true,
    genres: ["Acción", "Crimen", "Drama"],
    description: "Matt Murdock y Wilson Fisk retoman su guerra en las calles de Nueva York en la segunda temporada de la saga del Diablo de Hell's Kitchen.",
    poster: "https://image.tmdb.org/t/p/w500/gjum4yfMeZOu3upPstJHBPgTLFD.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/gjum4yfMeZOu3upPstJHBPgTLFD.jpg",
    seasons: 2,
    episodes: 9
  },
  {
    id: 152,
    title: "Ahsoka T2",
    year: 2026,
    type: "series",
    platform: "Disney",
    category: "Drama",
    rating: 8.3,
    featured: true,
    genres: ["Sci-Fi", "Drama", "Aventura"],
    description: "Ahsoka se adentra en la búsqueda del equilibrio de la Fuerza. El conflicto con Thrawn se intensifica mientras explora antiguas órdenes y conexiones con otras eras.",
    poster: "https://image.tmdb.org/t/p/w500/eiJeWeCAEZAmRppnXHiTWDcCd3Q.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/31GIcUUcdQPRkVtmdqgQWJMhXj1.jpg",
    seasons: 2,
    episodes: 8
  },
  {
    id: 153,
    title: "Solo asesinatos en el edificio T6",
    year: 2026,
    type: "series",
    platform: "Disney",
    category: "Comedias",
    rating: 8.4,
    featured: true,
    genres: ["Comedia", "Misterio", "Crimen"],
    description: "Steve Martin, Martin Short y Selena Gomez viajan a Londres para resolver un nuevo misterio. El trío de detectives más divertido de la TV regresa.",
    poster: "https://image.tmdb.org/t/p/w500/1yjFVQZuW8aofZ5Cgol8iImsVFp.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/WCnEPf4ZNPjszndmrFlDxZ5Uvd.jpg",
    seasons: 6,
    episodes: 10
  },
  {
    id: 154,
    title: "X-Men '97 T2",
    year: 2026,
    type: "series",
    platform: "Disney",
    category: "Infantiles",
    rating: 8.6,
    featured: false,
    genres: ["Animación", "Acción", "Aventura"],
    description: "Los X-Men afrontan nuevas crisis globales: la humanidad reacciona con miedo ante los mutantes, provocando tensiones políticas y enemigos clásicos renovados.",
    poster: "https://image.tmdb.org/t/p/w500/9Ycz7yYRf9V4jk3YXwcZhFtbNcF.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/iDnTAeR2WNA62XQG0ivtteDSjd5.jpg",
    seasons: 2,
    episodes: 10
  }
];

// ===== EXPORTS =====
export const getMovies = () => movies;
export const getTvShows = () => tvShows;
export const getAllMedia = () => [...movies, ...tvShows];
export const getFeatured = () => getAllMedia().filter(m => m.featured);
export const getTrending = () => getAllMedia().sort((a, b) => b.rating - a.rating).slice(0, 10);
export const getMediaById = (id) => getAllMedia().find(m => m.id === id);

// Categorías de películas
export const getMovieCategories = () => ["Terror", "Suspense", "Drama", "Históricas", "Comedias", "Infantiles"];
export const getMoviesByCategory = (category) => movies.filter(m => m.category === category);

// Plataformas de series
export const getPlatforms = () => ["Netflix", "HBO", "Movistar", "Apple", "Prime", "Disney"];
export const getSeriesByPlatform = (platform) => tvShows.filter(s => s.platform === platform);

// Categorías de series
export const getSeriesCategories = () => [...new Set(tvShows.map(s => s.category))];

export const searchMedia = (query) => {
  const q = query.toLowerCase();
  return getAllMedia().filter(m =>
    m.title.toLowerCase().includes(q) ||
    m.genres.some(g => g.toLowerCase().includes(q)) ||
    (m.platform && m.platform.toLowerCase().includes(q)) ||
    (m.category && m.category.toLowerCase().includes(q))
  );
};

export const getYears = () => {
  const years = [...new Set(getAllMedia().map(m => m.year))];
  return years.sort((a, b) => b - a);
};
    year: 2026,
    type: "movie",
    category: "Terror",
    rating: 7.0,
    featured: false,
    genres: ["Terror", "Acción", "Thriller"],
    description: "Un hombre es perseguido implacablemente por un grupo misterioso con métodos cada vez más sádicos en una noche interminable de supervivencia.",
    poster: "https://image.tmdb.org/t/p/w500/mIDMvrgKj8JjSTaKJMf2s7NECdM.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/mIDMvrgKj8JjSTaKJMf2s7NECdM.jpg",
    duration: "1h 42min",
    director: "Kirill Sokolov"
  },
  {
    id: 4,
    title: "Caminando con el diablo",
    year: 2026,
    type: "movie",
    category: "Terror",
    rating: 6.5,
    featured: false,
    genres: ["Terror", "Drama"],
    description: "Una joven descubre que su familia está vinculada a un pacto ancestral con una entidad demoníaca en los montes del norte de España.",
    poster: "https://image.tmdb.org/t/p/w500/dT8knVOBbnduYXeMkzsCbx57tIy.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/pOHicTKjzVfDaaB2xGi97JjfEcL.jpg",
    duration: "1h 50min",
    director: "Rubén Pérez Barrena"
  },

  // ===== SUSPENSE =====
  {
    id: 10,
    title: "El día de la revelación",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 8.5,
    featured: true,
    genres: ["Suspense", "Sci-Fi", "Drama"],
    description: "Steven Spielberg regresa al género que definió: la humanidad reacciona ante la prueba irrefutable de vida extraterrestre. ¿Y si la verdad estuviera a punto de ser revelada?",
    poster: "https://image.tmdb.org/t/p/w500/cEwmXRkShveQFIJDPQIJMKfJF0v.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/cEwmXRkShveQFIJDPQIJMKfJF0v.jpg",
    duration: "2h 20min",
    director: "Steven Spielberg"
  },
  {
    id: 11,
    title: "Spider-Man: Brand New Day",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 8.0,
    featured: true,
    genres: ["Acción", "Suspense", "Aventura"],
    description: "Peter Parker vuelve al anonimato total mientras enfrenta una Nueva York plagada de amenazas y un nuevo villano que conoce su mayor secreto.",
    poster: "https://image.tmdb.org/t/p/w500/z0GjufCxMjCPL4CmzPOofJN1vx0.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/z0GjufCxMjCPL4CmzPOofJN1vx0.jpg",
    duration: "2h 25min",
    director: "Destin Daniel Cretton"
  },
  {
    id: 12,
    title: "Supergirl: Woman of Tomorrow",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 7.6,
    featured: false,
    genres: ["Acción", "Suspense", "Sci-Fi"],
    description: "Kara Zor-El se embarca en una misión de venganza junto a una joven que ha perdido a su familia, descubriendo lo que significa ser una heroína.",
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/sAtoMqDVhNDQBc3QJL3RF6hlhGq.jpg",
    duration: "2h 10min",
    director: "Craig Gillespie"
  },
  {
    id: 13,
    title: "Los juegos del hambre: Amanecer en la cosecha",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 7.8,
    featured: true,
    genres: ["Suspense", "Acción", "Drama"],
    description: "La juventud de Haymitch Abernathy: lucha por sobrevivir en los Quincuagésimos Juegos del Hambre, donde se seleccionan el doble de tributos.",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    duration: "2h 30min",
    director: "Francis Lawrence"
  },
  {
    id: 14,
    title: "Proyecto Salvación",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 7.9,
    featured: false,
    genres: ["Suspense", "Sci-Fi", "Aventura"],
    description: "Un astronauta solitario en una misión desesperada para salvar la Tierra descubre que no está solo en el espacio.",
    poster: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    duration: "2h 15min",
    director: "Phil Lord, Christopher Miller"
  },
  {
    id: 15,
    title: "Peaky Blinders: El hombre inmortal",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 8.3,
    featured: true,
    genres: ["Suspense", "Crimen", "Drama"],
    description: "Tommy Shelby regresa durante la Segunda Guerra Mundial, arrastrado a los rincones más oscuros de Birmingham en misiones clandestinas.",
    poster: "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg",
    duration: "2h 30min",
    director: "Tom Harper"
  },
  {
    id: 16,
    title: "Street Fighter",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 7.1,
    featured: false,
    genres: ["Acción", "Suspense", "Aventura"],
    description: "Ambientada en 1993, Ryu y Ken son reclutados por Chun-Li para el Torneo Mundial de Guerreros, tras el que se esconde una conspiración mortal.",
    poster: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/b0PlSFdDwbyFAJlMFUwHCmRBCFo.jpg",
    duration: "2h 5min",
    director: "Kitao Sakurai"
  },
  {
    id: 17,
    title: "Shelter: El protector",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 7.0,
    featured: false,
    genres: ["Acción", "Suspense"],
    description: "Un exmilitar debe proteger a una familia refugiada en un búnker subterráneo cuando una amenaza desconocida arrasa la superficie.",
    poster: "https://image.tmdb.org/t/p/w500/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/1X7vow16X7CnCoexXh4H4F2yDJv.jpg",
    duration: "1h 55min",
    director: "Ric Roman Waugh"
  },
  {
    id: 18,
    title: "Cleaner: Rescate vertical",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 7.3,
    featured: false,
    genres: ["Acción", "Suspense", "Thriller"],
    description: "Un limpiacristales queda atrapado en un rascacielos tomado por terroristas y debe escalar planta a planta para rescatar a los rehenes.",
    poster: "https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg",
    duration: "1h 48min",
    director: "Martin Campbell"
  },
  {
    id: 19,
    title: "Águilas de El Cairo",
    year: 2026,
    type: "movie",
    category: "Suspense",
    rating: 7.4,
    featured: false,
    genres: ["Suspense", "Drama", "Thriller"],
    description: "Un agente encubierto se infiltra en una red de espionaje internacional con sede en El Cairo, donde las lealtades cambian a cada segundo.",
    poster: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nez7S.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    duration: "2h 0min",
    director: "Tarik Saleh"
  },

  // ===== DRAMA =====
  {
    id: 20,
    title: "Hamnet",
    year: 2026,
    type: "movie",
    category: "Drama",
    rating: 8.2,
    featured: true,
    genres: ["Drama", "Historia"],
    description: "La vida del hijo de Shakespeare y las raíces emocionales detrás de la creación de Hamlet. Agnes lidia con la enfermedad de su hijo en la Inglaterra del siglo XVI.",
    poster: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/AaV1YIdWKRUzEMqMYTNDIVgSMSp.jpg",
    duration: "2h 5min",
    director: "Chloé Zhao"
  },
  {
    id: 21,
    title: "Marty Supreme",
    year: 2026,
    type: "movie",
    category: "Drama",
    rating: 8.0,
    featured: true,
    genres: ["Drama", "Biografía"],
    description: "Timothée Chalamet interpreta a un joven ambicioso en la Nueva York de los 50 que se transforma de buscavidas en icono del tenis de mesa.",
    poster: "https://image.tmdb.org/t/p/w500/dKFaECtqxkYnRYIKFBR4usEfOFP.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/dKFaECtqxkYnRYIKFBR4usEfOFP.jpg",
    duration: "2h 29min",
    director: "Josh Safdie"
  },
  {
    id: 22,
    title: "Cumbres borrascosas",
    year: 2026,
    type: "movie",
    category: "Drama",
    rating: 7.8,
    featured: true,
    genres: ["Drama", "Romance"],
    description: "Margot Robbie y Jacob Elordi protagonizan la nueva adaptación de Emerald Fennell del clásico de Emily Brontë: obsesión, resentimiento y amor destructivo.",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK1DVfjko.jpg",
    duration: "2h 15min",
    director: "Emerald Fennell"
  },
  {
    id: 23,
    title: "I Swear (Incontrolable)",
    year: 2026,
    type: "movie",
    category: "Drama",
    rating: 7.5,
    featured: false,
    genres: ["Drama", "Biografía"],
    description: "La historia real de John Davidson, diagnosticado con síndrome de Tourette en su adolescencia, y su lucha por la comprensión y la visibilidad.",
    poster: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fMBs5CXKF4lik8M1JAF20RQI8AG.jpg",
    duration: "2h 0min",
    director: "Kirk Jones"
  },
  {
    id: 24,
    title: "Michael",
    year: 2026,
    type: "movie",
    category: "Drama",
    rating: 7.9,
    featured: true,
    genres: ["Drama", "Biografía", "Musical"],
    description: "El primer biopic cinematográfico de Michael Jackson, desde los Jackson Five hasta su consagración como Rey del Pop. Jaafar Jackson interpreta a su tío.",
    poster: "https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    duration: "2h 30min",
    director: "Antoine Fuqua"
  },
  {
    id: 25,
    title: "Amarga Navidad",
    year: 2026,
    type: "movie",
    category: "Drama",
    rating: 8.1,
    featured: true,
    genres: ["Drama"],
    description: "La nueva película de Pedro Almodóvar. Un drama íntimo y desgarrador ambientado durante las fiestas navideñas que explora las tensiones familiares.",
    poster: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlYj2O0gkHVcB0KMSIY7y.jpg",
    duration: "2h 10min",
    director: "Pedro Almodóvar"
  },
  {
    id: 26,
    title: "¡La novia!",
    year: 2026,
    type: "movie",
    category: "Drama",
    rating: 7.7,
    featured: false,
    genres: ["Drama", "Romance", "Fantasía"],
    description: "Maggie Gyllenhaal dirige a Christian Bale y Jessie Buckley en una reimaginación oscura y poética del mito de Frankenstein.",
    poster: "https://image.tmdb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/iICfelNPbQSOSi0pfGaw7xQrCAh.jpg",
    duration: "2h 0min",
    director: "Maggie Gyllenhaal"
  },
  {
    id: 27,
    title: "Digger",
    year: 2026,
    type: "movie",
    category: "Drama",
    rating: 8.0,
    featured: false,
    genres: ["Drama", "Comedia", "Sátira"],
    description: "Tom Cruise interpreta a Digger Rockwell, el hombre más poderoso del mundo que debe salvar a la humanidad de un gran desastre. Una sátira de Iñárritu.",
    poster: "https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/9ijMGlJKqcslswWUzTEwScm82Gs.jpg",
    duration: "2h 25min",
    director: "Alejandro González Iñárritu"
  },

  // ===== HISTÓRICAS =====
  {
    id: 30,
    title: "La odisea",
    year: 2026,
    type: "movie",
    category: "Históricas",
    rating: 9.0,
    featured: true,
    genres: ["Aventura", "Drama", "Historia"],
    description: "Christopher Nolan reinterpreta el poema homérico con Matt Damon, Tom Holland, Zendaya y Anne Hathaway. Ulises lucha por regresar a Ítaca tras la guerra de Troya.",
    poster: "https://image.tmdb.org/t/p/w500/hgA5hN1TjRfMgHxs4MChx8VMv3Z.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/vZm6Eo7MURipDkJu7BeAeM4hVFo.jpg",
    duration: "2h 50min",
    director: "Christopher Nolan"
  },
  {
    id: 31,
    title: "El último vikingo",
    year: 2026,
    type: "movie",
    category: "Históricas",
    rating: 7.3,
    featured: false,
    genres: ["Drama", "Historia", "Acción"],
    description: "La historia del último gran rey vikingo y su lucha desesperada por mantener viva una civilización en declive.",
    poster: "https://image.tmdb.org/t/p/w500/dT8knVOBbnduYXeMkzsCbx57tIy.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/pOHicTKjzVfDaaB2xGi97JjfEcL.jpg",
    duration: "2h 15min",
    director: "Anders Thomas Jensen"
  },
  {
    id: 32,
    title: "El mago del Kremlin",
    year: 2026,
    type: "movie",
    category: "Históricas",
    rating: 7.5,
    featured: false,
    genres: ["Drama", "Historia", "Thriller"],
    description: "Adaptación de la novela sobre Vladislav Surkov, el enigmático asesor político que controló la narrativa del Kremlin durante dos décadas.",
    poster: "https://image.tmdb.org/t/p/w500/z0GjufCxMjCPL4CmzPOofJN1vx0.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/z0GjufCxMjCPL4CmzPOofJN1vx0.jpg",
    duration: "2h 10min",
    director: "Olivier Assayas"
  },
  {
    id: 33,
    title: "La sombra de mi padre",
    year: 2026,
    type: "movie",
    category: "Históricas",
    rating: 7.1,
    featured: false,
    genres: ["Drama", "Historia"],
    description: "Un joven africano descubre los secretos del pasado colonial de su familia y las sombras que aún persisten en el presente.",
    poster: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    duration: "1h 55min",
    director: "Akinola Davies"
  },

  // ===== COMEDIAS =====
  {
    id: 40,
    title: "Torrente presidente",
    year: 2026,
    type: "movie",
    category: "Comedias",
    rating: 6.5,
    featured: true,
    genres: ["Comedia"],
    description: "Santiago Segura regresa con la franquicia más gamberra del cine español. Torrente se presenta a presidente del gobierno con resultados hilarantes.",
    poster: "https://image.tmdb.org/t/p/w500/b7Y5p0hwhtdRO9iPGv7HqmEZ3Kp.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/u0akMEfhZ5VCNiCP5VwLNsRLjTI.jpg",
    duration: "1h 50min",
    director: "Santiago Segura"
  },
  {
    id: 41,
    title: "El diablo viste de Prada 2",
    year: 2026,
    type: "movie",
    category: "Comedias",
    rating: 7.5,
    featured: true,
    genres: ["Comedia", "Drama"],
    description: "Meryl Streep, Anne Hathaway y Emily Blunt regresan. Miranda Priestly enfrenta el declive de las revistas impresas mientras Andy triunfa en el mundo digital.",
    poster: "https://image.tmdb.org/t/p/w500/mIDMvrgKj8JjSTaKJMf2s7NECdM.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/mIDMvrgKj8JjSTaKJMf2s7NECdM.jpg",
    duration: "2h 0min",
    director: "David Frankel"
  },
  {
    id: 42,
    title: "Jackass 5",
    year: 2026,
    type: "movie",
    category: "Comedias",
    rating: 6.8,
    featured: false,
    genres: ["Comedia"],
    description: "Johnny Knoxville y el equipo vuelven con retos, bromas y acrobacias tan peligrosas como descacharrantes. El caos sin filtros regresa.",
    poster: "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg",
    duration: "1h 40min",
    director: "Jeff Tremaine"
  },
  {
    id: 43,
    title: "Aída y vuelta",
    year: 2026,
    type: "movie",
    category: "Comedias",
    rating: 6.9,
    featured: false,
    genres: ["Comedia"],
    description: "Comedia española con Carmen Machi, Paco León y Miren Ibarguren. Una aventura cómica con personajes desternillantes.",
    poster: "https://image.tmdb.org/t/p/w500/cEwmXRkShveQFIJDPQIJMKfJF0v.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/cEwmXRkShveQFIJDPQIJMKfJF0v.jpg",
    duration: "1h 45min",
    director: "Secun de la Rosa"
  },
  {
    id: 44,
    title: "Altas capacidades",
    year: 2026,
    type: "movie",
    category: "Comedias",
    rating: 7.2,
    featured: false,
    genres: ["Comedia", "Drama"],
    description: "Una comedia dramática española sobre un grupo de superdotados que se reúnen en un centro de convivencia con resultados inesperados.",
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/sAtoMqDVhNDQBc3QJL3RF6hlhGq.jpg",
    duration: "1h 52min",
    director: "Víctor García León"
  },

  // ===== INFANTILES =====
  {
    id: 50,
    title: "Hoppers",
    year: 2026,
    type: "movie",
    category: "Infantiles",
    rating: 7.8,
    featured: true,
    genres: ["Animación", "Aventura", "Comedia"],
    description: "Nueva película de Pixar. Mabel descubre una tecnología que transfiere la conciencia humana a animales robóticos y 'salta' su mente a un castor.",
    poster: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/iHSwvRVsNBBngSAb6w2p70SQ7eR.jpg",
    duration: "1h 40min",
    director: "Daniel Chong"
  },
  {
    id: 51,
    title: "Super Mario Galaxy: La película",
    year: 2026,
    type: "movie",
    category: "Infantiles",
    rating: 7.5,
    featured: true,
    genres: ["Animación", "Aventura", "Comedia"],
    description: "Mario y Luigi son transportados más allá del Reino Champiñón. Con la ayuda de Rosalina y los Lumas, deberán salvar el universo.",
    poster: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    duration: "1h 35min",
    director: "Aaron Horvath, Michael Jelenic"
  },
  {
    id: 52,
    title: "Toy Story 5",
    year: 2026,
    type: "movie",
    category: "Infantiles",
    rating: 8.0,
    featured: true,
    genres: ["Animación", "Aventura", "Comedia"],
    description: "Pixar regresa a su saga más emblemática. Woody emprende un viaje para reencontrarse con antiguos amigos y descubrir qué significa pertenecer.",
    poster: "https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    duration: "1h 38min",
    director: "Andrew Stanton"
  },
  {
    id: 53,
    title: "Minions y Monstruos",
    year: 2026,
    type: "movie",
    category: "Infantiles",
    rating: 7.2,
    featured: false,
    genres: ["Animación", "Comedia", "Aventura"],
    description: "Los entrañables Minions regresan con nuevas aventuras hilarantes y caóticas conectadas al arco narrativo de Gru.",
    poster: "https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg",
    duration: "1h 30min",
    director: "Pierre Coffin"
  },
  {
    id: 54,
    title: "The Mandalorian and Grogu",
    year: 2026,
    type: "movie",
    category: "Infantiles",
    rating: 8.2,
    featured: true,
    genres: ["Aventura", "Sci-Fi", "Familiar"],
    description: "Din Djarin y Grogu llegan a la gran pantalla. Su búsqueda de un nuevo hogar los enfrenta a enemigos del pasado y al legado de los Jedi.",
    poster: "https://image.tmdb.org/t/p/w500/dKFaECtqxkYnRYIKFBR4usEfOFP.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/dKFaECtqxkYnRYIKFBR4usEfOFP.jpg",
    duration: "2h 5min",
    director: "Jon Favreau"
  },
  {
    id: 55,
    title: "Mary Anning y la playa de los dinosaurios",
    year: 2026,
    type: "movie",
    category: "Infantiles",
    rating: 7.0,
    featured: false,
    genres: ["Animación", "Aventura", "Familiar"],
    description: "La historia animada de Mary Anning, la joven paleontóloga que descubrió fósiles que cambiaron la ciencia en la costa de Dorset.",
    poster: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nez7S.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    duration: "1h 25min",
    director: "Marcel Barelli"
  }
];

const tvShows = [
  // ===== NETFLIX =====
  {
    id: 101,
    title: "Él y ella",
    year: 2026,
    type: "series",
    platform: "Netflix",
    category: "Suspense",
    rating: 8.0,
    featured: true,
    genres: ["Suspense", "Drama", "Thriller"],
    description: "Tessa Thompson y Jon Bernthal protagonizan este thriller: Anna investiga un asesinato en su pueblo natal y el detective la convierte en sospechosa. Toda historia tiene dos versiones.",
    poster: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlYj2O0gkHVcB0KMSIY7y.jpg",
    seasons: 1,
    episodes: 6
  },
  {
    id: 102,
    title: "Los Bridgerton T4",
    year: 2026,
    type: "series",
    platform: "Netflix",
    category: "Drama",
    rating: 8.3,
    featured: true,
    genres: ["Drama", "Romance"],
    description: "Benedict Bridgerton se enamora de la misteriosa Sophie Beckett en un baile de máscaras. Amor, secretos y tensiones sociales en la temporada más romántica.",
    poster: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/iHSwvRVsNBBngSAb6w2p70SQ7eR.jpg",
    seasons: 4,
    episodes: 8
  },
  {
    id: 103,
    title: "Salvador",
    year: 2026,
    type: "series",
    platform: "Netflix",
    category: "Drama",
    rating: 7.8,
    featured: false,
    genres: ["Drama", "Acción"],
    description: "Luis Tosar interpreta a un técnico de emergencias que descubre que su hija pertenece a un grupo ultra. Creada por Aitor Gabilondo, dirigida por Daniel Calparsoro.",
    poster: "https://image.tmdb.org/t/p/w500/dKFaECtqxkYnRYIKFBR4usEfOFP.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/dKFaECtqxkYnRYIKFBR4usEfOFP.jpg",
    seasons: 1,
    episodes: 8
  },
  {
    id: 104,
    title: "One Piece: Rumbo a la Grand Line T2",
    year: 2026,
    type: "series",
    platform: "Netflix",
    category: "Comedias",
    rating: 8.5,
    featured: true,
    genres: ["Aventura", "Acción", "Comedia"],
    description: "Luffy y los Sombrero de Paja navegan la Grand Line: islas impredecibles, piratas letales y fenómenos imposibles. Iñaki Godoy regresa como Luffy.",
    poster: "https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg",
    seasons: 2,
    episodes: 8
  },
  {
    id: 105,
    title: "Berlín y la dama del armiño T2",
    year: 2026,
    type: "series",
    platform: "Netflix",
    category: "Suspense",
    rating: 7.6,
    featured: false,
    genres: ["Suspense", "Crimen", "Drama"],
    description: "Pedro Alonso regresa como Berlín con un nuevo golpe en Sevilla: fingir robar la dama del armiño mientras su verdadero objetivo es un matrimonio que lo chantajea.",
    poster: "https://image.tmdb.org/t/p/w500/cEwmXRkShveQFIJDPQIJMKfJF0v.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/cEwmXRkShveQFIJDPQIJMKfJF0v.jpg",
    seasons: 2,
    episodes: 8
  },
  {
    id: 106,
    title: "Cien años de soledad T2",
    year: 2026,
    type: "series",
    platform: "Netflix",
    category: "Drama",
    rating: 8.7,
    featured: true,
    genres: ["Drama", "Fantasía"],
    description: "La segunda y última parte de la adaptación de la obra maestra de Gabriel García Márquez. Rodada íntegramente en Colombia con respaldo de la familia del autor.",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK1DVfjko.jpg",
    seasons: 2,
    episodes: 8
  },
  {
    id: 107,
    title: "Bronca T2",
    year: 2026,
    type: "series",
    platform: "Netflix",
    category: "Suspense",
    rating: 7.9,
    featured: false,
    genres: ["Suspense", "Drama", "Comedia"],
    description: "Oscar Isaac, Carey Mulligan y Cailee Spaeny. Una pareja presencia una pelea violenta que desencadena chantajes y tensiones en un exclusivo country club.",
    poster: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fMBs5CXKF4lik8M1JAF20RQI8AG.jpg",
    seasons: 2,
    episodes: 8
  },

  // ===== HBO =====
  {
    id: 110,
    title: "The Pitt T2",
    year: 2026,
    type: "series",
    platform: "HBO",
    category: "Drama",
    rating: 8.2,
    featured: false,
    genres: ["Drama"],
    description: "Noah Wyle regresa como el médico jefe Robby en la sala de urgencias de Pittsburgh. Cada episodio cubre en tiempo real una hora de un turno de 15 horas.",
    poster: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    seasons: 2,
    episodes: 15
  },
  {
    id: 111,
    title: "El caballero de los Siete Reinos",
    year: 2026,
    type: "series",
    platform: "HBO",
    category: "Drama",
    rating: 8.5,
    featured: true,
    genres: ["Drama", "Fantasía", "Aventura"],
    description: "Spin-off de Juego de Tronos basado en 'Cuentos de Dunk y Egg'. Ser Duncan y su escudero Egg recorren Poniente un siglo antes de los eventos de la saga principal.",
    poster: "https://image.tmdb.org/t/p/w500/hgA5hN1TjRfMgHxs4MChx8VMv3Z.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/vZm6Eo7MURipDkJu7BeAeM4hVFo.jpg",
    seasons: 1,
    episodes: 6
  },
  {
    id: 112,
    title: "Euphoria T3",
    year: 2026,
    type: "series",
    platform: "HBO",
    category: "Drama",
    rating: 8.4,
    featured: true,
    genres: ["Drama"],
    description: "Zendaya regresa como Rue. Los personajes, ya adultos, enfrentan consecuencias psicológicas del pasado: rupturas, ambiciones y búsqueda de identidad.",
    poster: "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg",
    seasons: 3,
    episodes: 8
  },
  {
    id: 113,
    title: "La Casa del Dragón T3",
    year: 2026,
    type: "series",
    platform: "HBO",
    category: "Drama",
    rating: 8.8,
    featured: true,
    genres: ["Drama", "Fantasía", "Acción"],
    description: "La Danza de los Dragones se intensifica: alianzas imposibles, ciudades arrasadas y dragones enfrentados en cielo abierto por el Trono de Hierro.",
    poster: "https://image.tmdb.org/t/p/w500/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    seasons: 3,
    episodes: 8
  },
  {
    id: 114,
    title: "Rooster",
    year: 2026,
    type: "series",
    platform: "HBO",
    category: "Comedias",
    rating: 7.8,
    featured: false,
    genres: ["Comedia", "Drama"],
    description: "Steve Carell regresa a la comedia TV. Un escritor en crisis lidia con su relación con su hija en un entorno universitario. Producida por Bill Lawrence.",
    poster: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    seasons: 1,
    episodes: 10
  },
  {
    id: 115,
    title: "Lanterns",
    year: 2026,
    type: "series",
    platform: "HBO",
    category: "Suspense",
    rating: 8.0,
    featured: true,
    genres: ["Suspense", "Sci-Fi", "Acción"],
    description: "Hal Jordan y John Stewart investigan un caso al estilo True Detective que conecta con el nuevo universo DC de James Gunn. Kyle Chandler y Aaron Pierre protagonizan.",
    poster: "https://image.tmdb.org/t/p/w500/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/1X7vow16X7CnCoexXh4H4F2yDJv.jpg",
    seasons: 1,
    episodes: 8
  },

  // ===== MOVISTAR =====
  {
    id: 120,
    title: "Riot Women",
    year: 2026,
    type: "series",
    platform: "Movistar",
    category: "Drama",
    rating: 7.5,
    featured: false,
    genres: ["Drama", "Acción"],
    description: "Un grupo de mujeres rebeldes lucha contra la opresión en una sociedad distópica en esta nueva producción original de Movistar Plus+.",
    poster: "https://image.tmdb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/iICfelNPbQSOSi0pfGaw7xQrCAh.jpg",
    seasons: 1,
    episodes: 8
  },
  {
    id: 121,
    title: "Outlander T8",
    year: 2026,
    type: "series",
    platform: "Movistar",
    category: "Drama",
    rating: 8.1,
    featured: true,
    genres: ["Drama", "Romance", "Historia"],
    description: "La temporada final de la épica saga de Claire y Jamie Fraser. Tras ocho temporadas de viajes en el tiempo, amor y guerra, la historia llega a su conclusión.",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    seasons: 8,
    episodes: 10
  },
  {
    id: 122,
    title: "Por cien millones",
    year: 2026,
    type: "series",
    platform: "Movistar",
    category: "Suspense",
    rating: 7.6,
    featured: false,
    genres: ["Suspense", "Drama", "Crimen"],
    description: "Un grupo de personas normales se enfrenta a un dilema moral cuando descubren cien millones de euros escondidos, desatando caos y traiciones.",
    poster: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/AaV1YIdWKRUzEMqMYTNDIVgSMSp.jpg",
    seasons: 1,
    episodes: 6
  },

  // ===== APPLE TV+ =====
  {
    id: 130,
    title: "Furtivo",
    year: 2026,
    type: "series",
    platform: "Apple",
    category: "Suspense",
    rating: 7.9,
    featured: true,
    genres: ["Suspense", "Drama", "Thriller"],
    description: "Un guardabosques descubre una red de caza furtiva que esconde algo mucho más siniestro en los bosques del norte de España. Producción de Apple TV+.",
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/sAtoMqDVhNDQBc3QJL3RF6hlhGq.jpg",
    seasons: 1,
    episodes: 8
  },
  {
    id: 131,
    title: "Mujeres imperfectas",
    year: 2026,
    type: "series",
    platform: "Apple",
    category: "Drama",
    rating: 7.7,
    featured: false,
    genres: ["Drama", "Comedia"],
    description: "Tres amigas muy diferentes navegan los retos de la vida moderna mientras intentan mantener viva su amistad en esta nueva serie de Apple TV+.",
    poster: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/b0PlSFdDwbyFAJlMFUwHCmRBCFo.jpg",
    seasons: 1,
    episodes: 10
  },

  // ===== PRIME VIDEO =====
  {
    id: 140,
    title: "Spider-Noir",
    year: 2026,
    type: "series",
    platform: "Prime",
    category: "Suspense",
    rating: 8.3,
    featured: true,
    genres: ["Suspense", "Acción", "Crimen"],
    description: "Nicolas Cage protagoniza la versión noir de Spider-Man: un detective privado en el Nueva York corrupto de los años 30 durante la Gran Depresión.",
    poster: "https://image.tmdb.org/t/p/w500/dT8knVOBbnduYXeMkzsCbx57tIy.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/pOHicTKjzVfDaaB2xGi97JjfEcL.jpg",
    seasons: 1,
    episodes: 8
  },
  {
    id: 141,
    title: "Blade Runner 2099",
    year: 2026,
    type: "series",
    platform: "Prime",
    category: "Suspense",
    rating: 8.5,
    featured: true,
    genres: ["Sci-Fi", "Suspense", "Drama"],
    description: "Michelle Yeoh protagoniza esta secuela ambientada 50 años después de 2049. La línea entre humanos y replicantes es más difusa que nunca.",
    poster: "https://image.tmdb.org/t/p/w500/z0GjufCxMjCPL4CmzPOofJN1vx0.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/z0GjufCxMjCPL4CmzPOofJN1vx0.jpg",
    seasons: 1,
    episodes: 6
  },
  {
    id: 142,
    title: "Invencible T4",
    year: 2026,
    type: "series",
    platform: "Prime",
    category: "Suspense",
    rating: 8.6,
    featured: true,
    genres: ["Animación", "Acción", "Suspense"],
    description: "Mark Grayson continúa su camino como el superhéroe más poderoso de la Tierra mientras enfrenta amenazas cósmicas y dilemas morales cada vez más complejos.",
    poster: "https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg",
    seasons: 4,
    episodes: 8
  },
  {
    id: 143,
    title: "El joven Sherlock",
    year: 2026,
    type: "series",
    platform: "Prime",
    category: "Suspense",
    rating: 7.7,
    featured: false,
    genres: ["Suspense", "Misterio", "Drama"],
    description: "Los años de formación de Sherlock Holmes: un joven brillante pero inadaptado comienza a resolver sus primeros casos en la Inglaterra victoriana.",
    poster: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nez7S.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    seasons: 1,
    episodes: 8
  },

  // ===== DISNEY+ =====
  {
    id: 150,
    title: "Wonder Man",
    year: 2026,
    type: "series",
    platform: "Disney",
    category: "Comedias",
    rating: 7.5,
    featured: true,
    genres: ["Comedia", "Acción", "Superhéroes"],
    description: "Simon Williams, actor fracasado, compite con Trevor Slattery por el papel de Wonder Man. Marvel mezcla comedia, acción y cine dentro del cine.",
    poster: "https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/9ijMGlJKqcslswWUzTEwScm82Gs.jpg",
    seasons: 1,
    episodes: 8
  },
  {
    id: 151,
    title: "Daredevil: Born Again T2",
    year: 2026,
    type: "series",
    platform: "Disney",
    category: "Suspense",
    rating: 8.5,
    featured: true,
    genres: ["Acción", "Crimen", "Drama"],
    description: "Matt Murdock y Wilson Fisk retoman su guerra en las calles de Nueva York en la segunda temporada de la saga del Diablo de Hell's Kitchen.",
    poster: "https://image.tmdb.org/t/p/w500/mIDMvrgKj8JjSTaKJMf2s7NECdM.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/mIDMvrgKj8JjSTaKJMf2s7NECdM.jpg",
    seasons: 2,
    episodes: 9
  },
  {
    id: 152,
    title: "Ahsoka T2",
    year: 2026,
    type: "series",
    platform: "Disney",
    category: "Drama",
    rating: 8.3,
    featured: true,
    genres: ["Sci-Fi", "Drama", "Aventura"],
    description: "Ahsoka se adentra en la búsqueda del equilibrio de la Fuerza. El conflicto con Thrawn se intensifica mientras explora antiguas órdenes y conexiones con otras eras.",
    poster: "https://image.tmdb.org/t/p/w500/b7Y5p0hwhtdRO9iPGv7HqmEZ3Kp.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/u0akMEfhZ5VCNiCP5VwLNsRLjTI.jpg",
    seasons: 2,
    episodes: 8
  },
  {
    id: 153,
    title: "Solo asesinatos en el edificio T6",
    year: 2026,
    type: "series",
    platform: "Disney",
    category: "Comedias",
    rating: 8.4,
    featured: true,
    genres: ["Comedia", "Misterio", "Crimen"],
    description: "Steve Martin, Martin Short y Selena Gomez viajan a Londres para resolver un nuevo misterio. El trío de detectives más divertido de la TV regresa.",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK1DVfjko.jpg",
    seasons: 6,
    episodes: 10
  },
  {
    id: 154,
    title: "X-Men '97 T2",
    year: 2026,
    type: "series",
    platform: "Disney",
    category: "Infantiles",
    rating: 8.6,
    featured: false,
    genres: ["Animación", "Acción", "Aventura"],
    description: "Los X-Men afrontan nuevas crisis globales: la humanidad reacciona con miedo ante los mutantes, provocando tensiones políticas y enemigos clásicos renovados.",
    poster: "https://image.tmdb.org/t/p/w500/dKFaECtqxkYnRYIKFBR4usEfOFP.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/dKFaECtqxkYnRYIKFBR4usEfOFP.jpg",
    seasons: 2,
    episodes: 10
  }
];

// ===== EXPORTS =====
export const getMovies = () => movies;
export const getTvShows = () => tvShows;
export const getAllMedia = () => [...movies, ...tvShows];
export const getFeatured = () => getAllMedia().filter(m => m.featured);
export const getTrending = () => getAllMedia().sort((a, b) => b.rating - a.rating).slice(0, 10);
export const getMediaById = (id) => getAllMedia().find(m => m.id === id);

// Categorías de películas
export const getMovieCategories = () => ["Terror", "Suspense", "Drama", "Históricas", "Comedias", "Infantiles"];
export const getMoviesByCategory = (category) => movies.filter(m => m.category === category);

// Plataformas de series
export const getPlatforms = () => ["Netflix", "HBO", "Movistar", "Apple", "Prime", "Disney"];
export const getSeriesByPlatform = (platform) => tvShows.filter(s => s.platform === platform);

// Categorías de series
export const getSeriesCategories = () => [...new Set(tvShows.map(s => s.category))];

export const searchMedia = (query) => {
  const q = query.toLowerCase();
  return getAllMedia().filter(m =>
    m.title.toLowerCase().includes(q) ||
    m.genres.some(g => g.toLowerCase().includes(q)) ||
    (m.platform && m.platform.toLowerCase().includes(q)) ||
    (m.category && m.category.toLowerCase().includes(q))
  );
};

export const getYears = () => {
  const years = [...new Set(getAllMedia().map(m => m.year))];
  return years.sort((a, b) => b - a);
};
